name: Java CI with Maven

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run Rest Assured tests
        run: mvn clean test

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: upload-results
          path: target/surefire-reports
